module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--color-bg) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        light: "rgb(var(--color-light) / <alpha-value>)",
        dark: "rgb(var(--color-dark) / <alpha-value>)",
        neutral: "rgb(var(--color-neutral) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        blue: "rgb(var(--color-blue) / <alpha-value>)",
        indigo: "rgb(var(--color-indigo) / <alpha-value>)",
        purple: "rgb(var(--color-purple) / <alpha-value>)",
        pink: "rgb(var(--color-pink) / <alpha-value>)",
        red: "rgb(var(--color-red) / <alpha-value>)",
        orange: "rgb(var(--color-orange) / <alpha-value>)",
        yellow: "rgb(var(--color-yellow) / <alpha-value>)",
        green: "rgb(var(--color-green) / <alpha-value>)",
        teal: "rgb(var(--color-teal) / <alpha-value>)",
        cyan: "rgb(var(--color-cyan) / <alpha-value>)",
        white: "rgb(var(--color-white) / <alpha-value>)",
        black: "rgb(var(--color-black) / <alpha-value>)",
        gray: "rgb(var(--color-gray) / <alpha-value>)",
      },
    },
  },
};